### ISSUE TITLE
使用中遇到的问题

### ISSUE THREAD

**Issue by longhunpeter** [TangXiaoLv/Android-Easy-MultiDex#3]
在实际运用中，打包后在4.2.2模拟器上运行，出现如下错误，是不是说明相关依赖没有在第一个main dex中呢，这里是极光推送的相关依赖。
thma E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      java.lang.ExceptionInInitializerError
                                                                          at cn.jpush.android.b.a(Unknown Source)
                                                                          at cn.jpush.android.b.a(Unknown Source)
                                                                          at cn.jpush.android.api.JPushInterface.init(Unknown Source)
                                                                          at com.ibreathcare.asthma.MyApplication.init(MyApplication.java:82)
                                                                          at com.ibreathcare.asthma.MyApplication.onCreate(MyApplication.java:65)
                                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
                                                                          at android.app.ActivityThread.access$1300(ActivityThread.java:141)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by TangXiaoLv** [comment]
@longhunpeter 不是，如果没在main dex 中会报java.lang.NoClassDefFound，你可以尝试将极光的代码全放入mian dex 中再测试下。-keep cn.jpush.android.**

**Comment by longhunpeter** [comment]
我大概看了，只是在4.2.2的模拟器会有类似的问题，在真机上是ok的
