### ISSUE TITLE
java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

### ISSUE THREAD

**Issue by xiakejian** [TangXiaoLv/Android-Easy-MultiDex#7]
08-29 17:21:17.634 31325-31325/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: xx, PID: 31325
                                                   java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{xx/xxx.SplashActivity}: java.lang.ClassNotFoundException: Didn't find class "xxx.SplashActivity" on path: DexPathList[[zip file "/data/app/xx-1/base.apk"],nativeLibraryDirectories=[/data/app/xx-1/lib/arm, /vendor/lib, /system/lib]]
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2252)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5298)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.v6.sixrooms.ui.phone.SplashActivity" on path: DexPathList[[zip file "/data/app/xx-1/base.apk"],nativeLibraryDirectories=[/data/app/xx-1/lib/arm, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2242)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5298) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705) 
                                                    Suppressed: java.lang.NoClassDefFoundError: xxx..SplashActivity
                                                       at dalvik.system.DexFile.defineClassNative(Native Method)
                                                       at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                       at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                       at dalvik.system.DexPathList.findClass(DexPathList.java:321)
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                            ... 14 more
                                                    Suppressed: java.lang.ClassNotFoundException: xxx..SplashActivity
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                            ... 13 more
                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by xiakejian** [comment]
`-just activity XXX.SplashActivity

#-----------附加类-----------

# 如果你想要某个包路径在maindex中，则使用 -keep 选项，即使他已经在分包的路径中.若为空，不保留任意类

# 保留单个类.

#-keep android.support.v7.app.AppCompatDialogFragment.class

# 这条配置可以指定这个包下类在第二及其他dex中.

#-split android.support.v?.**
#将全部类移出主Dex
-split **.**

# 不包含Android gradle 插件自动生成的miandex列表.(不用系统自带分包策略)

#-donot-use-suggest

# 不进行dex分包， 直到 dex 的id数量超过 65536.(设置自动执行分包策略)

#-auto-maindex

# 显示miandex的日志.

#-log-mainlist`

**Comment by TangXiaoLv** [comment]
@xiakejian 使用2.0.1插件试试

**Comment by djguruwap** [comment]
Check your menifest.xml file..
may be there is a small mistake...
